change on kafka and update documentation
interTwin-eu/dcnios pull request #25
Opened 2024-04-22 08:27 UTC by SergioLangaritaBenitez

2024-04-22 11:13 UTC, esparig requested changes
Good work on this PR! I've left some suggestions for consideration. Feel free to discuss or implement as you see fit.

2024-04-22 11:13 UTC, esparig commented on docpage/docs/02.-Inputs/02.1.-dcache.md
Please maintain the same structure throughout the documentation; giving a definition at the beginning of the section could be a good idea (see comments on 2.3-5).

2024-04-22 11:13 UTC, esparig commented on docpage/docs/02.-Inputs/02.2.-generic.md
Please maintain the same structure throughout the documentation; giving a definition at the beginning of the section could be a good idea (see comments on 2.3-5).

2024-04-22 11:13 UTC, esparig commented on docpage/docs/03.-Outputs/03.1.-OSCAR.md
Please maintain the same structure throughout the documentation; giving a definition at the beginning of the section could be a good idea (see comments on 2.3-5).

2024-04-23 11:38 UTC, SergioLangaritaBenitez commented
I changed the code and adapted it to the Python style guide (PEP 8). Also, I changed the documentation as it was required.

2024-04-23 16:07 UTC, esparig commented on cli/dcnios-cli.py
>                      updateComponent(dcache)
I would create an external function for this block of code and the same for the rest of the values (dCache, OSCAR, generic...). The resulting code would be easier to read and maintain.

2024-04-23 16:12 UTC, esparig commented on docpage/docs/02.-Inputs/Kafka.md
> +The connection between NiFi and Kafka employs SSL context,the SSL Protocol used by default is TLS, and the Truststore Type is PKCS12. SSL context only needs the Truststore filename and Truststore pas
Please, put a blank space after the comma.

2024-04-23 16:13 UTC, esparig commented on docpage/docs/02.-Inputs/SQS.md
> +SQS is the ProcessGroup that consumes an AWS SQS queue , is comprised of:
Please remove the extra blank space before the comma.

2024-04-23 16:15 UTC, esparig commented on docpage/docs/02.-Inputs/dcache.md
> +dCache is the ProcessGroup that keep listen into dCache instance, is comprised of:
How about?: "dCache is the ProcessGroup that monitors dCache instances for events"

2024-04-23 16:16 UTC, esparig commented on docpage/docs/02.-Inputs/dcache.md
>  - Endpoint, user and password
Use Oxford comma here: "Endpoint, user, and password."

2024-04-23 16:17 UTC, esparig commented on docpage/docs/02.-Inputs/dcache.md
>  - Folder where active listening
Folder to be monitored

2024-04-23 16:20 UTC, esparig commented on docpage/docs/02.-Inputs/generic.md
> +- The path of your ProcessGroup (.json file)
Could you explain to me what you mean by this paragraph?

2024-04-23 16:20 UTC, esparig commented on docpage/docs/AWS.md
> +> :warning: **DCNiOS can use some AWS services**: This section clarifies the configuration required to use the credentials!
I don't think this should be a warning.

2024-04-23 16:26 UTC, esparig commented on docpage/docs/AWS.md
> +AWS_DEFAULT_REGION is mandatory in any source that uses AWS of the configuration file. Right now, the ProcessGroup that uses AWS credentials are:
Please, we need to review the documentation texts out of the PR.

2024-06-10 11:56 UTC, merged